---
- hosts: "masters,workers"
  remote_user: centos
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: Verify br_netfilter enable 
       shell: |
              cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
              br_netfilter
              EOF
              cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              EOF
              sudo sysctl --system
  
     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

 
     - name: Add Docker repo
       get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
       become: yes
     
     
     - name: Install docker
       shell: |
               sudo yum install docker-ce-20.10.13 docker-ce-cli-20.10.13 containerd.io-1.5.10 -y
     
 
     - name: Start Docker service
       service:
        name: docker
        state: started
        enabled: yes
       become: yes

     - name: Add user centos to docker group
       user:
        name: centos
        groups: docker
        append: yes
       become: yes   

     - name: install kubernetes repo
       shell: |
               cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo  
               [kubernetes]
               name=Kubernetes
               baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
               enabled=1
               gpgcheck=1
               repo_gpgcheck=0
               gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
               EOF

     - name: Disable selinux command
       shell: | 
               sudo setenforce 0
               sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

     - name: install kubelet kubeadm kubectl
       shell: |
               sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes 
               sudo systemctl enable --now kubelet   

    
     - name: Configure docker daemon repo
       shell: |
               cat <<EOF | sudo tee /etc/docker/daemon.json  
               {
               "exec-opts": ["native.cgroupdriver=systemd"]
               }
               EOF

     
     - name: Restart service docker
       service:
         name: docker
         state: restarted

     - name: Remove the CRI
       shell: |
               sudo rm -rf /etc/containerd/config.toml
               sudo systemctl restart containerd
